name: Deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.3

        # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
      - name: Install dependencies
        run: pnpm i

      # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
      - name: Build Astro
        run: pnpm run build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: muffindevx-summarify-web
          entrypoint: server/entry.mjs
          root: dist
